# Generated by Django 4.0.1 on 2022-02-12 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reportConsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reportTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
