# Generated by Django 4.0.1 on 2022-02-12 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_reportconsent_task_reporttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reportConsent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reportTime',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
