# Generated by Django 4.0.1 on 2022-02-12 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='consent',
            field=models.BooleanField(default=False, help_text='Uncheck to stop receiving reports'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), help_text='All times are in UTC 24hr format.', null=True),
        ),
    ]
