# Generated by Django 4.0.1 on 2022-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='n/a', max_length=100),
        ),
    ]
