# Generated by Django 4.0.1 on 2022-02-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_report_consent_alter_report_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='external_id',
        ),
    ]
