# Generated by Django 4.0.1 on 2022-02-14 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_report_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='All times are in UTC 24hr format.'),
        ),
    ]
