name: Django CI

on:
  push:
    branches:
      - "*"
jobs:
  django-test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests with coverage
        run: |
          coverage run manage.py test -v 2
      - name: coverage report
        run: |
          coverage report
      - name: flake8 linting
        run: |
          flake8 --exit-zero --statistics
